# Generated by Django 3.2.14 on 2022-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ksdhas', upload_to='pics'),
            preserve_default=False,
        ),
    ]
